# fly.toml app configuration file generated for bustripplanner-backend on 2026-04-15T18:49:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bustripplanner-backend'
primary_region = 'ord'

[build]

[env]
  GTFS_REFRESH_HOURS = '24'
  NODE_ENV = 'production'
  PORT = '8787'

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
